# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec095def2f6e99092cae6c66ce2a1f72874701bb4269c576efe41116dec9dc77f016ae952f61623324e34f51e2ecfece5d3c8d9e662726f1a61bffc38405f00

test:
  secret_key_base: ba9ade28903830886ae7f37816c3c0a7be2fc074c2e1e9ac2174cfabadddb1d519b4f013db1f055f52a1b185a16975ddb3e7d22405f877611b4b9a4e1dc62e42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
